---
title: "Report for the Course Project in Reproducible Research"
author: "Sven"
date: "21 September 2017"
output: github_document
---

### Libraries
```{r echo=TRUE}
library(fasttime)
library(knitr)
library(ggplot2)
library(data.table)
setwd("C:\\Users\\Sven\\Desktop\\Coursera\\RepResearch\\RepData_PeerAssessment1\\")
opts_chunk$set(dev="png", fig.path="figure/")
```

### Loading and preprocessing the data
```{r echo=TRUE}
activity <- fread("activity.csv", na.strings="NA", colClasses = c("steps" = "double"))   #read data
activity[, date := fastPOSIXct(date)]                                                    #convert to date
```


### What is mean total number of steps taken per day?
```{r echo=TRUE}
activitygrouped <- activity[, .(steps = sum(steps, na.rm = T)), by="date"]             #aggregate by day
activitygrouped[, .(mean=mean(steps, na.rm = T), median=median(steps, na.rm = T))]     #Calculate and report the mean and median total number of steps taken per day
ggplot(data=activitygrouped, aes(steps)) + geom_histogram(bins=10)                     #Histogram of the total number of steps taken each day
activity
```

### What is the average daily activity pattern?
```{r echo=TRUE}
steps <- activity[, .(mean = mean(steps, na.rm = T)), by = "interval"]
ggplot(steps, aes(x=interval, y=mean)) +  geom_line()            #Time series plot of the average number of steps taken
steps[which.max(mean)]                                    #The 5-minute interval that, on average, contains the maximum number of steps
```


### Imputing missing values
```{r echo=TRUE}
activity[is.na(steps), .N]                                                              # Total Number of rows with missing values
activity_imputed <- activity[, .(date, steps, interval, MeanSteps = mean(steps, na.rm = T)), by=.(week = data.table::week(date))]    # calculate mean of week
activity_imputed[is.na(steps), steps := MeanSteps][, MeanSteps := NULL]                 # replace missing values with mean 
activity_imputed_agg <- activity_imputed[, .(steps = sum(steps, na.rm = T)), by="date"]     # aggregate by day
activity_imputed_agg[, .(mean=mean(steps, na.rm = T), median=median(steps, na.rm = T))]     # Calculate and report the mean and median total number of steps taken per day
ggplot(data=activity_imputed_agg, aes(steps)) + geom_histogram(bins=10)                     # Histogram of the total number of steps taken each day
```

Imputing increase the mean and median value!


### Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}
activity_imputed[, weekday := as.factor(ifelse(weekdays(fastPOSIXct(date)) %in% c("Samstag", "Sonntag"), "weekend", "weekday"))]
activity_imputed <- activity_imputed[, .(mean = mean(steps, na.rm = T)), by = c("weekday","interval")]
ggplot(activity_imputed, aes(x=interval, y=mean)) +  
        geom_line() +           #Time series plot of the average number of steps taken
        facet_wrap(~weekday, ncol = 1)
```

