---
title: "Report for the Course Project in Reproducible Research"
author: "Sven"
date: "21 September 2017"
output: html_document
---

### Loading and preprocessing the datay
```{r echo=TRUE}
library(data.table)
library(fasttime)
setwd("C:\\Users\\Sven\\Desktop\\Coursera\\RepResearch\\RepData_PeerAssessment1\\")
AMD <- fread("activity.csv", na.strings="NA", colClasses = c("steps" = "double"))   #read data
AMD[, date := fastPOSIXct(date)]                #convert to date
```


# der median ist doch falsch
### What is mean total number of steps taken per day?
```{r echo=TRUE}
AMDwithoutNA <- AMD[, .(steps=sum(steps), mean=mean(steps), median=median(steps)), by="date"]     #aggregate by day and Mean and median number of steps taken each day
AMDwithoutNA <- AMDwithoutNA[!is.na(steps)] #remove NA 
library(ggplot2)
ggplot(AMDwithoutNA, aes(x=date, y=steps)) +  geom_col()            #Histogram of the total number of steps taken each day
AMDwithoutNA
```



### What is the average daily activity pattern?
```{r echo=TRUE}
ggplot(AMDwithoutNA, aes(x=date, y=mean)) +  geom_line()            #Time series plot of the average number of steps taken
AMDwithoutNA[which.max(mean)] #The 5-minute interval that, on average, contains the maximum number of steps
```



### Imputing missing values
```{r}
AMD[is.na(steps), .N]# Total Number of rows with missing values
AMD[, MeanSteps := mean(steps, na.rm = T), by=.(week(date)) # calculate mean of week
    ][is.na(steps), steps := MeanSteps, by=.(week(date)) # replace missing values with mean 
      ][, MeanSteps := NULL]
AMD <- AMD[, .(steps=sum(steps), mean=mean(steps), median=median(steps)), by="date"]     #aggregate by day and Mean and median number of steps taken each day
ggplot(AMD, aes(x=date, y=steps)) +  geom_col()            #Histogram of the total number of steps taken each day
AMD
```



### Are there differences in activity patterns between weekdays and weekends?